org: jaggahaws
app: kanban-board-serverless
service: kanban-board-serverless

provider:
  name: aws
  runtime: python3.8

plugins:
  - serverless-offline

# Routing requests for http://localhost:3000/dev.
functions:
  hello:
    handler: kanbanBoardController.hello
    events:
      - http:
          path: /
          method: get
  get:
    handler: kanbanBoardController.get
    events:
      - http:
          path: /tasks
          method: get
  post:
    handler: kanbanBoardController.create
    events:
      - http:
          path: /tasks
          method: post
  patch:
    handler: kanbanBoardController.update
    events:
      - http:
          path: /tasks/{id}
          method: patch
