org: jaggahaws
app: kanban-board-serverless
service: kanban-board-serverless

provider:
  name: aws
  runtime: python3.8

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get
